language: node_js
node_js:
    - "9"
sudo: false
branches:
    only:
    - master

install:
  - npm install
  - npm install -g react-native-cli

script:
    - react-native run-android
    - react-native run-ios